package enums;

public enum CardAbilityEnum {
	
	PLUS_ONE_CARD,
	PLUS_ONE_ACTION,
	PLUS_ONE_COIN,
	PLUS_ONE_BUY,
	TRASH_UP_TO_FOUR_CARDS_FROM_YOUR_HAND,
	DISCARD_ANY_NUMBER_OF_CARDS_THEN_DRAW_THAT_MANY,
	GAIN_A_CARD_COSTING_UP_TO_FOUR,
	TRASH_A_CARD_FROM_YOUR_HAND_GAIN_A_CARD_COSTING_UP_TO_TWO_MORE_THAN_IT,
	EACH_OTHER_PLAYER_DISCARDS_DOWN_TO_THREE_CARDS_IN_HAND,
	WORTH_ONE_VICTORY_POINT_PER_TEN_CARDS_YOU_HAVE_ROUND_DOWN,
	EACH_OTHER_PLAYER_GAINS_A_CURSE,

}
